// Code generated by Wire. DO NOT EDIT.

//go:generate wire
package di

import (
	"net/http"

	"student_service_app/backend/internal/config"
	"student_service_app/backend/internal/db"
	authhandler "student_service_app/backend/internal/handler/auth"
	classcoursehandler "student_service_app/backend/internal/handler/classcourse"
	enrollmenthandler "student_service_app/backend/internal/handler/enrollment"
	expensehandler "student_service_app/backend/internal/handler/expense"
	paymenthandler "student_service_app/backend/internal/handler/payment"
	receipthandler "student_service_app/backend/internal/handler/receipt"
	reporthandler "student_service_app/backend/internal/handler/report"
	settingshandler "student_service_app/backend/internal/handler/settings"
	studenthandler "student_service_app/backend/internal/handler/student"
	teacherhandler "student_service_app/backend/internal/handler/teacher"
	"student_service_app/backend/internal/logger"
	authrepo "student_service_app/backend/internal/repository/auth"
	classcourserepo "student_service_app/backend/internal/repository/classcourse"
	enrollmentrepo "student_service_app/backend/internal/repository/enrollment"
	expenserepo "student_service_app/backend/internal/repository/expense"
	paymentrepo "student_service_app/backend/internal/repository/payment"
	receiptrepo "student_service_app/backend/internal/repository/receipt"
	reportrepo "student_service_app/backend/internal/repository/report"
	settingsrepo "student_service_app/backend/internal/repository/settings"
	studentrepo "student_service_app/backend/internal/repository/student"
	teacherrepo "student_service_app/backend/internal/repository/teacher"
	"student_service_app/backend/internal/server"
	authsvc "student_service_app/backend/internal/service/auth"
	classcoursesvc "student_service_app/backend/internal/service/classcourse"
	enrollmentsvc "student_service_app/backend/internal/service/enrollment"
	expensesvc "student_service_app/backend/internal/service/expense"
	paymentsvc "student_service_app/backend/internal/service/payment"
	receiptsvc "student_service_app/backend/internal/service/receipt"
	reportsvc "student_service_app/backend/internal/service/report"
	settingssvc "student_service_app/backend/internal/service/settings"
	studentsvc "student_service_app/backend/internal/service/student"
	teachersvc "student_service_app/backend/internal/service/teacher"
)

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.New(configConfig)
	if err != nil {
		return nil, err
	}
	dbDB, err := db.NewPostgres(configConfig)
	if err != nil {
		return nil, err
	}
	validatorValidate := NewValidator()
	base := NewBase(validatorValidate)
	authRepository := authrepo.NewPostgresRepository(dbDB)
	settingsRepository := settingsrepo.NewPostgresRepository(dbDB)
	tokenManager := authsvc.NewTokenManager(configConfig)
	authService := authsvc.NewService(dbDB, authRepository, settingsRepository, tokenManager)
	authHandler := authhandler.NewHandler(base, authService)
	studentRepository := studentrepo.NewPostgresRepository(dbDB)
	studentService := studentsvc.NewService(studentRepository)
	studentHandler := studenthandler.NewHandler(base, studentService)
	teacherRepository := teacherrepo.NewPostgresRepository(dbDB)
	teacherService := teachersvc.NewService(teacherRepository)
	teacherHandler := teacherhandler.NewHandler(base, teacherService)
	classcourseRepository := classcourserepo.NewPostgresRepository(dbDB)
	classcourseService := classcoursesvc.NewService(classcourseRepository, teacherRepository)
	classcourseHandler := classcoursehandler.NewHandler(base, classcourseService)
	enrollmentRepository := enrollmentrepo.NewPostgresRepository(dbDB)
	paymentRepository := paymentrepo.NewPostgresRepository(dbDB)
	receiptRepository := receiptrepo.NewPostgresRepository(dbDB)
	enrollmentService := enrollmentsvc.NewService(dbDB, enrollmentRepository, studentRepository, classcourseRepository, paymentRepository, receiptRepository, settingsRepository)
	enrollmentHandler := enrollmenthandler.NewHandler(base, enrollmentService)
	paymentService := paymentsvc.NewService(dbDB, paymentRepository, enrollmentRepository, receiptRepository, settingsRepository)
	paymentHandler := paymenthandler.NewHandler(base, paymentService)
	expenseRepository := expenserepo.NewPostgresRepository(dbDB)
	expenseService := expensesvc.NewService(expenseRepository, teacherRepository, classcourseRepository)
	expenseHandler := expensehandler.NewHandler(base, expenseService)
	receiptService := receiptsvc.NewService(receiptRepository)
	receiptHandler := receipthandler.NewHandler(receiptService)
	reportRepository := reportrepo.NewPostgresRepository(dbDB)
	reportService := reportsvc.NewService(reportRepository)
	reportHandler := reporthandler.NewHandler(reportService)
	settingsService := settingssvc.NewService(settingsRepository)
	settingsHandler := settingshandler.NewHandler(base, settingsService)
	handlers := NewHandlers(authHandler, studentHandler, teacherHandler, classcourseHandler, enrollmentHandler, paymentHandler, expenseHandler, receiptHandler, reportHandler, settingsHandler)
	handler := server.NewRouter(loggerLogger, tokenManager, handlers)
	httpServer := server.NewHTTPServer(configConfig, handler)
	app := &App{
		Config: configConfig,
		Logger: loggerLogger,
		Server: httpServer,
	}
	return app, nil
}

var _ *http.Server
